(function (global) {
    global.siteProjects = [
        {
            priority: 100,
            name: 'Shopware Admin Toolbar',
            href: 'https://github.com/WariKoda/WakoPluginAdminToolbar',
            repo: 'WariKoda/WakoPluginAdminToolbar',
            descriptionKey: 'hero.project1.description',
            owner: 'WariKoda',
            lead: '@nibra180',
            leadHref: 'https://github.com/nibra180',
            leadClass: 'text-terminal-green',
            cardClass: '',
            showInPinned: true,
            showInWarikoda: true,
            warikodaName: 'Shopware 6 Admin Toolbar Plugin',
            warikodaDescriptionKey: 'warikoda.project1Description',
            warikodaLabel: '[oss]',
            warikodaLabelClass: 'text-terminal-green',
            badges: [
                {
                    label: 'Shopware 6',
                    className: 'text-[10px] text-terminal-green border border-terminal-green/30 bg-terminal-green/10 rounded px-1.5 py-0.5',
                },
            ],
        },
        {
            priority: 80,
            name: 'Focus Journal App',
            href: 'https://github.com/WariKoda/FocusJournal',
            repo: 'WariKoda/FocusJournal',
            descriptionKey: 'hero.project2.description',
            owner: 'WariKoda',
            lead: '@bdgraue',
            leadHref: 'https://github.com/bdgraue',
            leadClass: 'text-terminal-cyan',
            cardClass: '',
            showInPinned: true,
            showInWarikoda: true,
            warikodaName: 'Focus Journal',
            warikodaDescriptionKey: 'warikoda.project2Description',
            warikodaLabel: '[app]',
            warikodaLabelClass: 'text-terminal-cyan',
            badges: [
                {
                    label: 'Flutter',
                    className: 'text-[10px] text-terminal-cyan border border-terminal-cyan/30 bg-terminal-cyan/10 rounded px-1.5 py-0.5',
                },
            ],
        },
        {
            priority: 90,
            name: 'drift',
            href: 'https://github.com/WariKoda/drift',
            repo: 'WariKoda/drift',
            descriptionKey: 'hero.project3.description',
            owner: 'WariKoda',
            lead: '@nibra180',
            leadHref: 'https://github.com/nibra180',
            leadClass: 'text-terminal-purple',
            cardClass: '',
            showInPinned: true,
            showInWarikoda: true,
            warikodaName: 'drift',
            warikodaDescriptionKey: 'warikoda.project3Description',
            warikodaLabel: '[tui]',
            warikodaLabelClass: 'text-terminal-purple',
            badges: [
                {
                    label: 'TUI',
                    className: 'text-[10px] text-terminal-purple border border-terminal-purple bg-terminal-surface/40 rounded px-1.5 py-0.5',
                },
                {
                    label: 'Go',
                    className: 'text-[10px] text-terminal-green border border-terminal-green/30 bg-terminal-green/10 rounded px-1.5 py-0.5',
                },
            ],
        },
    ];
})(typeof window !== 'undefined' ? window : globalThis);
