[defaults]
  port = 0
  user = ""

[[hosts]]
  name = "nibraun.de"
  hostname = "202.61.233.87"
  port = 21
  user = "hosting208980"
  root_path = "/tui.nibraun.de"
  protocol = "ftp"
  [hosts.auth]
    type = "password"
    password = "&eRow76I&tPrrcr0"
    key_file = ""
    passphrase = ""
